# permissions for end users to edit testnfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testnf-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testnf-operator
    app.kubernetes.io/part-of: testnf-operator
    app.kubernetes.io/managed-by: kustomize
  name: testnf-editor-role
rules:
- apiGroups:
  - crd.vmware.com
  resources:
  - testnfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.vmware.com
  resources:
  - testnfs/status
  verbs:
  - get
